name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Run when changes are pushed to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'   # Specify the version you want

      # Step 3: Initialize Terraform with the API token for authentication
      - name: Terraform Init
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}   # Use GitHub secret for the token
        run: terraform init

      # Step 4: Run Terraform Plan
      - name: Terraform Plan
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}   # Use GitHub secret for the token
        run: terraform plan

      # Step 5: Apply Terraform changes
      - name: Terraform Apply
        environment:
          name: production   # Link this step to the "production" environment
          url: ${{ steps.plan.outputs.url }}   # Optional: URL to view the plan
        if: success()  # Only run this step if Plan was successful
        run: terraform apply -auto-approve
