name: Terraform Plan

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'  # Specify the version of Terraform to use

      # Step 3: Initialize Terraform
      - name: Terraform Init
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}  # Use GitHub secret for the Terraform Cloud token
        run: terraform init

      # Step 4: Run Terraform Plan
      - name: Terraform Plan
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}  # Use GitHub secret for the Terraform Cloud token
        run: terraform plan
