name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]  # Trigger when Terraform Plan workflow is completed
    types:
      - completed

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan  # Ensure Terraform Plan ran successfully

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      # Step 3: Terraform Init
      - name: Terraform Init
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        run: terraform init

      # Step 4: Terraform Apply (Requires manual approval)
      - name: Terraform Apply
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        run: terraform apply -auto-approve
