name: 'Terraform Plan'
## ...
on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "area51coder"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "azureterra"
  CONFIG_DIRECTORY: "./"
## ...


jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}   # Use GitHub secret for the token
        run: terraform init

      - name: Terraform Plan
        run: terraform plan